WebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using DiscordBot;

namespace WebUI.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            var thread = new Thread(() =>
            {
                new Program().MainAsync().GetAwaiter().GetResult();
            });
            thread.Start();
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebUI/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataLibrary.Shop;

namespace WebUI.Controllers
{
    public class ShopController : Controller
    {
        // GET: Shop
        public ActionResult Index()
        {
            var itemlist = ShopItems.GetShopItems;
            return View(itemlist);
        }

        public ActionResult Edit(int id)
        {
            var item = ShopItems.GetShopItems.FirstOrDefault(x => x.Id == id);
            return View(item);
        }

        [HttpPost]
        public ActionResult Edit(ShopItem item)
        { 
            ShopItems.ReplaceItem(item);
            return RedirectToAction("Index");
        }
    }
}

WebUI/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataLibrary;
using DataLibrary.Static_Data;

namespace WebUI.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        public ActionResult Index()
        {
            var database = new Mock();
            var users = database.Users.ToList();
            var user = users[0];
            return View(user);
            
        }
    }
}

WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebUI/Views/Shop/Edit.cshtml
@model DataLibrary.Shop.ShopItem

@{
    ViewBag.Title = "title";
}
<div class="col-lg-5">
<h2>Edit</h2>
@using (Html.BeginForm("Edit", "Shop", FormMethod.Post))
{
    @Html.LabelFor(x => x.Name, "Name")
    ;
    @Html.TextBoxFor(x => x.Name, new {@class = "form-control"})
    <br/>
    @Html.LabelFor(x => x.Description, "Description")
    @Html.TextBoxFor(x => x.Description, new {@class = "form-control"})
    <br/>
    @Html.LabelFor(x => x.Game, "Game")
    ;
    @Html.TextBoxFor(x => x.Game, new {@class = "form-control"})
    <br/>
    @Html.LabelFor(x => x.Series, "Series")
    @Html.TextBoxFor(x => x.Series, new {@class = "form-control"})
    <br/>
    @Html.LabelFor(x => x.Condition, "Condition")
    @Html.TextBoxFor(x => x.Condition, new {@class = "form-control"})
    <br/>
    @Html.LabelFor(x => x.Price, "Price")
    ;
    @Html.TextBoxFor(x => x.Price, new {@type = "number", @class = "form-control"})
    <br/>
    @Html.LabelFor(x => x.ImageUrl, "Image URL")
    @Html.TextBoxFor(x => x.ImageUrl, new {@class = "form-control"})
    <br/>
    @Html.LabelFor(x => x.Buyable, "Buyable")
    @Html.CheckBoxFor(x => x.Buyable, new {@class = "form-control"})
    <br/>
    @Html.LabelFor(x => x.Code, "Code")
    @Html.TextBoxFor(x => x.Code, new {@class = "form-control"})
    <br/>
    <button type="submit" class="btn btn-success">Save</button>
}
</div>
<div class="col-lg-5">
    <h2>Image Preview</h2>
    <img src="@Model.ImageUrl" width="75%" height="50%" style="padding-top: 1em"/>
</div>

WebUI/Views/Shop/Index.cshtml
@model System.Collections.Generic.List<DataLibrary.Shop.ShopItem>

@{
    ViewBag.Title = "title";
}


<div class="container">
    <h2>Shop</h2>
    <p>Current items in store:</p>
    <table class="table table-hover">
        <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Description</th>
            <th>Price</th>
            <th>Buyable</th>
            <th>Code</th>
            <th>Condition</th>
            <th>Game</th>
            <th>Series</th>
            <th></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>@item.Description</td>
                <td>@item.Price</td>
                <td>@item.Buyable</td>
                <td>@item.Code</td>
                <td>@item.Condition</td>
                <td>@item.Game</td>
                <td>@item.Series</td>
                <td><a href="Shop/Edit/@item.Id" class="btn btn-info">Edit</a></td>
                @*<td><button class="btn btn-info">Edit</button></td>*@
                <td><button class="btn btn-danger">Remove</button></td>
            </tr>
        }
        </tbody>
    </table>
</div>

WebUI/Views/User/Index.cshtml
@using Microsoft.Ajax.Utilities
@model DataLibrary.Discord.Implemented.DiscordUser

@{
    ViewBag.Title = "title";
}

<h2>@Model.Name</h2>
<b>Joined:</b> @Model.CreationDate.ToLongDateString()
@if (!string.IsNullOrEmpty(Model.SmashAccount.Username) && (bool) Model.SmashAccount.IsVerified)
{
    <br/>
    <b>Anther's Ladder Account:</b> @Model.SmashAccount.Username
}